// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoln-RgXpxG78OnkxmJoDxgXchk0og-Us',
    appId: '1:819929475244:web:5207849cb75ddbf1121709',
    messagingSenderId: '819929475244',
    projectId: 'spotifyappmax',
    authDomain: 'spotifyappmax.firebaseapp.com',
    storageBucket: 'spotifyappmax.firebasestorage.app',
    measurementId: 'G-DWFBHSMWZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh8s4il6i0y33-KPzBHuDvaX3JT4WOQsI',
    appId: '1:819929475244:android:a41016261220089b121709',
    messagingSenderId: '819929475244',
    projectId: 'spotifyappmax',
    storageBucket: 'spotifyappmax.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAemYOhs6tbGpWhkUMBXS0VZTZcp-T3iaU',
    appId: '1:819929475244:ios:7980e03033cb67ac121709',
    messagingSenderId: '819929475244',
    projectId: 'spotifyappmax',
    storageBucket: 'spotifyappmax.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAemYOhs6tbGpWhkUMBXS0VZTZcp-T3iaU',
    appId: '1:819929475244:ios:7980e03033cb67ac121709',
    messagingSenderId: '819929475244',
    projectId: 'spotifyappmax',
    storageBucket: 'spotifyappmax.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoln-RgXpxG78OnkxmJoDxgXchk0og-Us',
    appId: '1:819929475244:web:32d047c8d8a2a14f121709',
    messagingSenderId: '819929475244',
    projectId: 'spotifyappmax',
    authDomain: 'spotifyappmax.firebaseapp.com',
    storageBucket: 'spotifyappmax.firebasestorage.app',
    measurementId: 'G-BDX33VVLVX',
  );
}
